import type { TopologyData } from '../types/topo';

// Node IDs are auto-generated by slugifying the label.
// e.g. "Core-Router-1" → "core-router-1", "Dist-SW-1" → "dist-sw-1"
// Edge source/target must match these slugified values.
const TEMPLATE: TopologyData = {
  nodes: [
    {
      id: 'core-router-1',
      label: 'Core-Router-1',
      type: 'router',
      ip: '10.0.0.1',
      mac: 'AA:BB:CC:DD:EE:01',
      vendor: 'Cisco',
      model: 'ASR9000',
      location: 'DC-A / Rack-1',
      group: 'g-core',
      status: 'up',
      interfaces: [
        { name: 'GigabitEthernet0/0', ip: '10.0.0.1', speed: 10000, status: 'up' },
        { name: 'GigabitEthernet0/1', ip: '10.1.0.254', speed: 10000, status: 'up' }
      ]
    },
    {
      id: 'core-router-2',
      label: 'Core-Router-2',
      type: 'router',
      ip: '10.0.0.2',
      vendor: 'Cisco',
      model: 'ASR9000',
      location: 'DC-A / Rack-2',
      group: 'g-core',
      status: 'up',
      interfaces: []
    },
    {
      id: 'firewall-1',
      label: 'Firewall-1',
      type: 'firewall',
      ip: '10.0.1.1',
      vendor: 'Palo Alto',
      model: 'PA-3220',
      location: 'DC-A / Rack-3',
      group: 'g-dmz',
      status: 'up',
      interfaces: []
    },
    {
      id: 'dist-sw-1',
      label: 'Dist-SW-1',
      type: 'switch',
      ip: '10.1.0.1',
      vendor: 'Juniper',
      model: 'EX4300',
      location: 'Floor-2 / IDF-A',
      group: 'g-dist',
      status: 'up',
      interfaces: []
    },
    {
      id: 'access-sw-1',
      label: 'Access-SW-1',
      type: 'switch',
      ip: '10.1.1.1',
      vendor: 'Juniper',
      model: 'EX2300',
      location: 'Floor-2 / IDF-A',
      group: 'g-floor2',
      status: 'warning',
      interfaces: []
    },
    {
      id: 'ap-floor2-01',
      label: 'AP-Floor2-01',
      type: 'ap',
      ip: '10.1.1.10',
      vendor: 'Aruba',
      model: 'AP-515',
      location: 'Floor-2 / Zone-B',
      group: 'g-floor2',
      status: 'up',
      interfaces: []
    },
    {
      id: 'app-server-1',
      label: 'App-Server-1',
      type: 'server',
      ip: '10.2.0.10',
      vendor: 'Dell',
      model: 'PowerEdge R750',
      location: 'DC-A / Rack-5',
      group: 'g-servers',
      status: 'up',
      interfaces: []
    },
    {
      id: 'workstation-01',
      label: 'Workstation-01',
      type: 'endpoint',
      ip: '10.1.1.101',
      location: 'Floor-2 / Desk-14',
      group: 'g-floor2',
      status: 'down',
      interfaces: []
    }
  ],
  edges: [
    {
      id: 'link-0',
      source: 'core-router-1',
      target: 'core-router-2',
      sourcePort: 'GigabitEthernet0/2',
      targetPort: 'GigabitEthernet0/2',
      bandwidth: 100000,
      utilizationOut: 0.32,
      utilizationIn: 0.18,
      protocol: 'fiber',
      status: 'up'
    },
    {
      id: 'link-1',
      source: 'core-router-1',
      target: 'firewall-1',
      sourcePort: 'GigabitEthernet0/3',
      targetPort: 'ethernet1/1',
      bandwidth: 10000,
      utilizationOut: 0.55,
      utilizationIn: 0.42,
      protocol: 'fiber',
      status: 'up'
    },
    {
      id: 'link-2',
      source: 'core-router-1',
      target: 'dist-sw-1',
      sourcePort: 'GigabitEthernet0/1',
      targetPort: 'ge-0/0/0',
      bandwidth: 10000,
      utilizationOut: 0.71,
      utilizationIn: 0.60,
      protocol: 'fiber',
      status: 'up'
    },
    {
      id: 'link-3',
      source: 'dist-sw-1',
      target: 'access-sw-1',
      sourcePort: 'ge-0/0/1',
      targetPort: 'ge-0/0/0',
      bandwidth: 1000,
      utilizationOut: 0.88,
      utilizationIn: 0.75,
      protocol: 'ethernet',
      status: 'up'
    },
    {
      id: 'link-4',
      source: 'access-sw-1',
      target: 'ap-floor2-01',
      sourcePort: 'ge-0/0/2',
      targetPort: 'eth0',
      bandwidth: 1000,
      utilizationOut: 0.20,
      utilizationIn: 0.05,
      protocol: 'ethernet',
      status: 'up'
    },
    {
      id: 'link-5',
      source: 'access-sw-1',
      target: 'workstation-01',
      sourcePort: 'ge-0/0/3',
      targetPort: 'eth0',
      bandwidth: 1000,
      utilizationOut: 0,
      utilizationIn: 0,
      protocol: 'ethernet',
      status: 'down'
    },
    {
      id: 'link-6',
      source: 'core-router-2',
      target: 'app-server-1',
      sourcePort: 'GigabitEthernet0/1',
      targetPort: 'eth0',
      bandwidth: 10000,
      utilizationOut: 0.45,
      utilizationIn: 0.38,
      protocol: 'fiber',
      status: 'up'
    }
  ],
  groups: [
    { id: 'g-core',    label: 'Core Layer',    type: 'subnet' },
    { id: 'g-dmz',     label: 'DMZ',           type: 'subnet' },
    { id: 'g-dist',    label: 'Distribution',  type: 'vlan'   },
    { id: 'g-floor2',  label: 'Floor 2',       type: 'floor'  },
    { id: 'g-servers', label: 'Server Farm',   type: 'rack'   }
  ]
};

/** Trigger a browser download of a file by blob content. */
function triggerDownload(content: string, filename: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/** Download the topology import template as JSON. */
export function downloadTemplateJSON(): void {
  triggerDownload(
    JSON.stringify(TEMPLATE, null, 2),
    'topology-template.json',
    'application/json',
  );
}

// ── CSV helpers ──────────────────────────────────────────────────────────────

const DEVICES_HEADER =
  'label,type,ip,mac,vendor,model,location,group,status';

const LINKS_HEADER =
  'source,target,sourcePort,targetPort,bandwidth,utilizationOut,utilizationIn,protocol,status';

function row(...fields: (string | number | undefined)[]): string {
  return fields.map((f) => f ?? '').join(',');
}

const DEVICES_CSV = [
  DEVICES_HEADER,
  row('Core-Router-1',   'router',   '10.0.0.1',  'AA:BB:CC:DD:EE:01', 'Cisco',     'ASR9000',        'DC-A / Rack-1',    'g-core',    'up'),
  row('Core-Router-2',   'router',   '10.0.0.2',  '',                  'Cisco',     'ASR9000',        'DC-A / Rack-2',    'g-core',    'up'),
  row('Firewall-1',      'firewall', '10.0.1.1',  '',                  'Palo Alto', 'PA-3220',        'DC-A / Rack-3',    'g-dmz',     'up'),
  row('Dist-SW-1',       'switch',   '10.1.0.1',  '',                  'Juniper',   'EX4300',         'Floor-2 / IDF-A',  'g-dist',    'up'),
  row('Access-SW-1',     'switch',   '10.1.1.1',  '',                  'Juniper',   'EX2300',         'Floor-2 / IDF-A',  'g-floor2',  'warning'),
  row('AP-Floor2-01',    'ap',       '10.1.1.10', '',                  'Aruba',     'AP-515',         'Floor-2 / Zone-B', 'g-floor2',  'up'),
  row('App-Server-1',    'server',   '10.2.0.10', '',                  'Dell',      'PowerEdge R750', 'DC-A / Rack-5',    'g-servers', 'up'),
  row('Workstation-01',  'endpoint', '10.1.1.101','',                  '',          '',               'Floor-2 / Desk-14','g-floor2',  'down'),
].join('\n');

const LINKS_CSV = [
  LINKS_HEADER,
  row('Core-Router-1', 'Core-Router-2', 'GigabitEthernet0/2', 'GigabitEthernet0/2', 100000, 0.32, 0.18, 'fiber',    'up'),
  row('Core-Router-1', 'Firewall-1',    'GigabitEthernet0/3', 'ethernet1/1',         10000, 0.55, 0.42, 'fiber',    'up'),
  row('Core-Router-1', 'Dist-SW-1',     'GigabitEthernet0/1', 'ge-0/0/0',            10000, 0.71, 0.60, 'fiber',    'up'),
  row('Dist-SW-1',     'Access-SW-1',   'ge-0/0/1',           'ge-0/0/0',             1000, 0.88, 0.75, 'ethernet', 'up'),
  row('Access-SW-1',   'AP-Floor2-01',  'ge-0/0/2',           'eth0',                 1000, 0.20, 0.05, 'ethernet', 'up'),
  row('Access-SW-1',   'Workstation-01','ge-0/0/3',           'eth0',                 1000, 0,    0,    'ethernet', 'down'),
  row('Core-Router-2', 'App-Server-1',  'GigabitEthernet0/1', 'eth0',                10000, 0.45, 0.38, 'fiber',    'up'),
].join('\n');

/** Download devices template as CSV. */
export function downloadTemplateDevicesCSV(): void {
  triggerDownload(DEVICES_CSV, 'topology-template-devices.csv', 'text/csv');
}

/** Download links template as CSV. */
export function downloadTemplateLinksCSV(): void {
  triggerDownload(LINKS_CSV, 'topology-template-links.csv', 'text/csv');
}
